import Head from "next/head";
import React, {useEffect, useState} from "react";
import Canvas from "@/components/Canvas/Canvas";
import styles from "../styles/Home.module.scss";
export default function Home() {

    const [width, setWidth] = useState(0);
    const [height, setHeight] = useState(0);

    useEffect(() => {
        setWidth(window.innerWidth);
        setHeight(window.innerHeight);
    }, []);

  return (
      <>
          <Head>
              <title>Particlism</title>
              <meta name="description" content="Generated by create next app"/>
              <meta name="viewport" content="width=device-width, initial-scale=1"/>
              <link rel="icon" href="/particlism.png"/>
          </Head>
          <div className={styles['particlism-simulator']}>
              <Canvas width={width} height={height}/>
          </div>
      </>
  );
}
