import Head from "next/head";
import React, { useEffect, useState } from "react";
import { Settings } from "lucide-react";
import Canvas from "@/components/Canvas/Canvas";
import SideDrawer from "@/components/SideDrawer/SideDrawer";
import { randomColor, randomForce } from "@/particleConfig";
import styles from "../styles/Home.module.scss";

interface ColorConfig {
    color: string;
    number: number;
    attractions: { [key: string]: number };
}

const decodeConfig = (value: string): ColorConfig[] | null => {
    try {
        const parsed = JSON.parse(atob(value.replace(/-/g, "+").replace(/_/g, "/")));
        if (!Array.isArray(parsed) || parsed.length < 1 || parsed.length > 10) return null;

        const colors = parsed.map(config => config.color);
        if (new Set(colors).size !== colors.length) return null;

        return parsed.every(config =>
            /^#[0-9a-f]{6}$/i.test(config.color) &&
            Number.isInteger(config.number) && config.number >= 10 && config.number <= 1000 &&
            config.attractions && typeof config.attractions === "object" &&
            colors.every((color: string) =>
                typeof config.attractions[color] === "number" &&
                config.attractions[color] >= -1 && config.attractions[color] <= 1
            )
        ) ? parsed : null;
    } catch {
        return null;
    }
};

const encodeConfig = (config: ColorConfig[]) =>
    btoa(JSON.stringify(config)).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");

export default function Home() {
    const [width, setWidth] = useState(0);
    const [height, setHeight] = useState(0);
    const [isDrawerOpen, setIsDrawerOpen] = useState(true);
    const [configReady, setConfigReady] = useState(false);
    const [colorsConfig, setColorsConfig] = useState<ColorConfig[]>([
        { color: "#e6194b", number: 200, attractions: {} },
        { color: "#3cb44b", number: 200, attractions: {} },
        { color: "#ffe119", number: 200, attractions: {} }
    ]);

    useEffect(() => {
        setWidth(window.innerWidth);
        setHeight(window.innerHeight);

        const sharedConfig = decodeConfig(new URLSearchParams(window.location.search).get("config") || "");
        if (sharedConfig) {
            setColorsConfig(sharedConfig);
            setConfigReady(true);
            return;
        }

        const colors: string[] = [];
        while (colors.length < 3) colors.push(randomColor(colors));

        // Randomness runs client-side so server and browser HTML still match.
        setColorsConfig(colors.map(color => ({
            color,
            number: 200,
            attractions: colors.reduce((acc, otherColor) => {
                acc[otherColor] = randomForce();
                return acc;
            }, {} as { [key: string]: number })
        })));
        setConfigReady(true);
    }, []);

    useEffect(() => {
        if (!configReady) return;
        const url = new URL(window.location.href);
        url.searchParams.set("config", encodeConfig(colorsConfig));
        window.history.replaceState(null, "", url);
    }, [colorsConfig, configReady]);

    const handleDrawerClose = () => {
        setIsDrawerOpen(false);
    };

    const handleDrawerOpen = () => {
        setIsDrawerOpen(true);
    };

    return (
        <>
            <Head>
                <title>Particlism</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/particlism.png" />
            </Head>
            <div className={styles['particlism-simulator']}>
                <Canvas width={width} height={height} colorsConfig={colorsConfig} setColorsConfig={setColorsConfig} />
                <SideDrawer
                    isOpen={isDrawerOpen}
                    onClose={handleDrawerClose}
                    colorsConfig={colorsConfig}
                    setColorsConfig={setColorsConfig}
                />
                {!isDrawerOpen && (
                    <button
                        className={styles['open-drawer-button']}
                        onClick={handleDrawerOpen}
                        title="Open simulation controls"
                    >
                        <Settings size={20} />
                    </button>
                )}
            </div>
        </>
    );
}
